-- GENERATE BY ./scripts/generate.ts
-- DO NOT EDIT IT MANUALLY


module Stories exposing (allCategories)

import Ant.Element.Icons
import Ant.Icon exposing (height, width)
import Element exposing (Element)


type alias Category msg =
    { name : String
    , outlined : List (Element msg)
    , filled : List (Element msg)
    , twoTone : List (Element msg)
    }


allCategories : List (Category msg)
allCategories =
    [ direction
    , suggestion
    , editor
    , data
    , logo
    , other
    ]


direction : Category msg
direction =
    { name = "Directional Icons"
    , outlined =
        [ Ant.Element.Icons.stepBackwardOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.stepForwardOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.fastBackwardOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.fastForwardOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.shrinkOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.arrowsAltOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.downOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.upOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.leftOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.rightOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.caretUpOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.caretDownOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.caretLeftOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.caretRightOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.upCircleOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.downCircleOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.leftCircleOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.rightCircleOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.doubleRightOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.doubleLeftOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.verticalLeftOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.verticalRightOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.verticalAlignTopOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.verticalAlignMiddleOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.verticalAlignBottomOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.forwardOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.backwardOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.rollbackOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.enterOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.retweetOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.swapOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.swapLeftOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.swapRightOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.arrowUpOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.arrowDownOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.arrowLeftOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.arrowRightOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.playCircleOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.upSquareOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.downSquareOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.leftSquareOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.rightSquareOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.loginOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.logoutOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.menuFoldOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.menuUnfoldOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.borderBottomOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.borderHorizontalOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.borderInnerOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.borderOuterOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.borderLeftOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.borderRightOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.borderTopOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.borderVerticleOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.picCenterOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.picLeftOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.picRightOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.radiusBottomleftOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.radiusBottomrightOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.radiusUpleftOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.radiusUprightOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.fullscreenOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.fullscreenExitOutlined [ width 64, height 64 ]
        ]
    , filled =
        [ Ant.Element.Icons.stepBackwardFilled [ width 64, height 64 ]
        , Ant.Element.Icons.stepForwardFilled [ width 64, height 64 ]
        , Ant.Element.Icons.fastBackwardFilled [ width 64, height 64 ]
        , Ant.Element.Icons.fastForwardFilled [ width 64, height 64 ]
        , Ant.Element.Icons.caretUpFilled [ width 64, height 64 ]
        , Ant.Element.Icons.caretDownFilled [ width 64, height 64 ]
        , Ant.Element.Icons.caretLeftFilled [ width 64, height 64 ]
        , Ant.Element.Icons.caretRightFilled [ width 64, height 64 ]
        , Ant.Element.Icons.upCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.downCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.leftCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.rightCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.forwardFilled [ width 64, height 64 ]
        , Ant.Element.Icons.backwardFilled [ width 64, height 64 ]
        , Ant.Element.Icons.playCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.upSquareFilled [ width 64, height 64 ]
        , Ant.Element.Icons.downSquareFilled [ width 64, height 64 ]
        , Ant.Element.Icons.leftSquareFilled [ width 64, height 64 ]
        , Ant.Element.Icons.rightSquareFilled [ width 64, height 64 ]
        ]
    , twoTone =
        [ Ant.Element.Icons.upCircleTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.downCircleTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.leftCircleTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.rightCircleTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.playCircleTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.upSquareTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.downSquareTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.leftSquareTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.rightSquareTwoTone [ width 64, height 64 ]
        ]
    }


suggestion : Category msg
suggestion =
    { name = "Suggested Icons"
    , outlined =
        [ Ant.Element.Icons.questionOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.questionCircleOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.plusOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.plusCircleOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.pauseOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.pauseCircleOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.minusOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.minusCircleOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.plusSquareOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.minusSquareOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.infoOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.infoCircleOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.exclamationOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.exclamationCircleOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.closeOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.closeCircleOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.closeSquareOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.checkOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.checkCircleOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.checkSquareOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.clockCircleOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.warningOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.issuesCloseOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.stopOutlined [ width 64, height 64 ]
        ]
    , filled =
        [ Ant.Element.Icons.questionCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.plusCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.pauseCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.minusCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.plusSquareFilled [ width 64, height 64 ]
        , Ant.Element.Icons.minusSquareFilled [ width 64, height 64 ]
        , Ant.Element.Icons.infoCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.exclamationCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.closeCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.closeSquareFilled [ width 64, height 64 ]
        , Ant.Element.Icons.checkCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.checkSquareFilled [ width 64, height 64 ]
        , Ant.Element.Icons.clockCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.warningFilled [ width 64, height 64 ]
        , Ant.Element.Icons.stopFilled [ width 64, height 64 ]
        ]
    , twoTone =
        [ Ant.Element.Icons.questionCircleTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.plusCircleTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.pauseCircleTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.minusCircleTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.plusSquareTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.minusSquareTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.infoCircleTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.exclamationCircleTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.closeCircleTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.closeSquareTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.checkCircleTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.checkSquareTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.clockCircleTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.warningTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.stopTwoTone [ width 64, height 64 ]
        ]
    }


editor : Category msg
editor =
    { name = "Editor Icons"
    , outlined =
        [ Ant.Element.Icons.editOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.formOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.copyOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.scissorOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.deleteOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.snippetsOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.diffOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.highlightOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.alignCenterOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.alignLeftOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.alignRightOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.bgColorsOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.boldOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.italicOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.underlineOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.strikethroughOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.redoOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.undoOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.zoomInOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.zoomOutOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.fontColorsOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.fontSizeOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.lineHeightOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.dashOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.smallDashOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.sortAscendingOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.sortDescendingOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.dragOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.orderedListOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.unorderedListOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.radiusSettingOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.columnWidthOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.columnHeightOutlined [ width 64, height 64 ]
        ]
    , filled =
        [ Ant.Element.Icons.editFilled [ width 64, height 64 ]
        , Ant.Element.Icons.copyFilled [ width 64, height 64 ]
        , Ant.Element.Icons.deleteFilled [ width 64, height 64 ]
        , Ant.Element.Icons.snippetsFilled [ width 64, height 64 ]
        , Ant.Element.Icons.diffFilled [ width 64, height 64 ]
        , Ant.Element.Icons.highlightFilled [ width 64, height 64 ]
        ]
    , twoTone =
        [ Ant.Element.Icons.editTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.copyTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.deleteTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.snippetsTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.diffTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.highlightTwoTone [ width 64, height 64 ]
        ]
    }


data : Category msg
data =
    { name = "Data Icons"
    , outlined =
        [ Ant.Element.Icons.areaChartOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.pieChartOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.barChartOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.dotChartOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.lineChartOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.radarChartOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.heatMapOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.fallOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.riseOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.stockOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.boxPlotOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.fundOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.slidersOutlined [ width 64, height 64 ]
        ]
    , filled =
        [ Ant.Element.Icons.pieChartFilled [ width 64, height 64 ]
        , Ant.Element.Icons.boxPlotFilled [ width 64, height 64 ]
        , Ant.Element.Icons.fundFilled [ width 64, height 64 ]
        , Ant.Element.Icons.slidersFilled [ width 64, height 64 ]
        ]
    , twoTone =
        [ Ant.Element.Icons.pieChartTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.boxPlotTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.fundTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.slidersTwoTone [ width 64, height 64 ]
        ]
    }


logo : Category msg
logo =
    { name = "Brand and Logos"
    , outlined =
        [ Ant.Element.Icons.androidOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.appleOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.windowsOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.ieOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.chromeOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.githubOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.aliwangwangOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.dingdingOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.weiboSquareOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.weiboCircleOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.taobaoCircleOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.html5Outlined [ width 64, height 64 ]
        , Ant.Element.Icons.weiboOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.twitterOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.wechatOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.youtubeOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.alipayCircleOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.taobaoOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.skypeOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.qqOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.mediumWorkmarkOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.gitlabOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.mediumOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.linkedinOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.googlePlusOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.dropboxOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.facebookOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.codepenOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.codeSandboxOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.amazonOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.googleOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.codepenCircleOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.alipayOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.antDesignOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.antCloudOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.aliyunOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.zhihuOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.slackOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.slackSquareOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.behanceOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.behanceSquareOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.dribbbleOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.dribbbleSquareOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.instagramOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.yuqueOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.alibabaOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.yahooOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.redditOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.sketchOutlined [ width 64, height 64 ]
        ]
    , filled =
        [ Ant.Element.Icons.androidFilled [ width 64, height 64 ]
        , Ant.Element.Icons.appleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.windowsFilled [ width 64, height 64 ]
        , Ant.Element.Icons.chromeFilled [ width 64, height 64 ]
        , Ant.Element.Icons.githubFilled [ width 64, height 64 ]
        , Ant.Element.Icons.aliwangwangFilled [ width 64, height 64 ]
        , Ant.Element.Icons.weiboSquareFilled [ width 64, height 64 ]
        , Ant.Element.Icons.weiboCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.taobaoCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.html5Filled [ width 64, height 64 ]
        , Ant.Element.Icons.wechatFilled [ width 64, height 64 ]
        , Ant.Element.Icons.youtubeFilled [ width 64, height 64 ]
        , Ant.Element.Icons.alipayCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.skypeFilled [ width 64, height 64 ]
        , Ant.Element.Icons.gitlabFilled [ width 64, height 64 ]
        , Ant.Element.Icons.linkedinFilled [ width 64, height 64 ]
        , Ant.Element.Icons.facebookFilled [ width 64, height 64 ]
        , Ant.Element.Icons.codeSandboxCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.codepenCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.slackSquareFilled [ width 64, height 64 ]
        , Ant.Element.Icons.behanceSquareFilled [ width 64, height 64 ]
        , Ant.Element.Icons.dribbbleSquareFilled [ width 64, height 64 ]
        , Ant.Element.Icons.instagramFilled [ width 64, height 64 ]
        , Ant.Element.Icons.yuqueFilled [ width 64, height 64 ]
        , Ant.Element.Icons.yahooFilled [ width 64, height 64 ]
        ]
    , twoTone =
        [ Ant.Element.Icons.html5TwoTone [ width 64, height 64 ]
        ]
    }


other : Category msg
other =
    { name = "Application Icons"
    , outlined =
        [ Ant.Element.Icons.accountBookOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.aimOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.alertOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.apartmentOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.apiOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.appstoreAddOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.appstoreOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.audioOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.audioMutedOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.auditOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.bankOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.barcodeOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.barsOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.bellOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.blockOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.bookOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.borderOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.borderlessTableOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.branchesOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.bugOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.buildOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.bulbOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.calculatorOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.calendarOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.cameraOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.carOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.carryOutOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.ciCircleOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.ciOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.clearOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.cloudDownloadOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.cloudOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.cloudServerOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.cloudSyncOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.cloudUploadOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.clusterOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.codeOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.coffeeOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.commentOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.compassOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.compressOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.consoleSqlOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.contactsOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.containerOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.controlOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.copyrightCircleOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.copyrightOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.creditCardOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.crownOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.customerServiceOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.dashboardOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.databaseOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.deleteColumnOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.deleteRowOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.deliveredProcedureOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.deploymentUnitOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.desktopOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.dingtalkOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.disconnectOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.dislikeOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.dollarCircleOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.dollarOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.downloadOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.ellipsisOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.environmentOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.euroCircleOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.euroOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.exceptionOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.expandAltOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.expandOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.experimentOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.exportOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.eyeOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.eyeInvisibleOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.fieldBinaryOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.fieldNumberOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.fieldStringOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.fieldTimeOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.fileAddOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.fileDoneOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.fileExcelOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.fileExclamationOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.fileOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.fileGifOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.fileImageOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.fileJpgOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.fileMarkdownOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.filePdfOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.filePptOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.fileProtectOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.fileSearchOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.fileSyncOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.fileTextOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.fileUnknownOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.fileWordOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.fileZipOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.filterOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.fireOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.flagOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.folderAddOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.folderOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.folderOpenOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.folderViewOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.forkOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.formatPainterOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.frownOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.functionOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.fundProjectionScreenOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.fundViewOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.funnelPlotOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.gatewayOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.gifOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.giftOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.globalOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.goldOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.groupOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.hddOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.heartOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.historyOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.homeOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.hourglassOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.idcardOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.importOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.inboxOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.insertRowAboveOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.insertRowBelowOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.insertRowLeftOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.insertRowRightOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.insuranceOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.interactionOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.keyOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.laptopOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.layoutOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.likeOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.lineOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.linkOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.loading3QuartersOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.loadingOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.lockOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.macCommandOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.mailOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.manOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.medicineBoxOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.mehOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.menuOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.mergeCellsOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.messageOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.mobileOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.moneyCollectOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.monitorOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.moreOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.nodeCollapseOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.nodeExpandOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.nodeIndexOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.notificationOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.numberOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.oneToOneOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.paperClipOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.partitionOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.payCircleOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.percentageOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.phoneOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.pictureOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.playSquareOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.poundCircleOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.poundOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.poweroffOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.printerOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.profileOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.projectOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.propertySafetyOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.pullRequestOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.pushpinOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.qrcodeOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.readOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.reconciliationOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.redEnvelopeOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.reloadOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.restOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.robotOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.rocketOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.rotateLeftOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.rotateRightOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.safetyCertificateOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.safetyOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.saveOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.scanOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.scheduleOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.searchOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.securityScanOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.selectOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.sendOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.settingOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.shakeOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.shareAltOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.shopOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.shoppingCartOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.shoppingOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.sisternodeOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.skinOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.smileOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.solutionOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.soundOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.splitCellsOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.starOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.subnodeOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.switcherOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.syncOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.tableOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.tabletOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.tagOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.tagsOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.teamOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.thunderboltOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.toTopOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.toolOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.trademarkCircleOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.trademarkOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.transactionOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.translationOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.trophyOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.ungroupOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.unlockOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.uploadOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.usbOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.userAddOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.userDeleteOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.userOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.userSwitchOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.usergroupAddOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.usergroupDeleteOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.verifiedOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.videoCameraAddOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.videoCameraOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.walletOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.whatsAppOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.wifiOutlined [ width 64, height 64 ]
        , Ant.Element.Icons.womanOutlined [ width 64, height 64 ]
        ]
    , filled =
        [ Ant.Element.Icons.accountBookFilled [ width 64, height 64 ]
        , Ant.Element.Icons.alertFilled [ width 64, height 64 ]
        , Ant.Element.Icons.alipaySquareFilled [ width 64, height 64 ]
        , Ant.Element.Icons.amazonCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.amazonSquareFilled [ width 64, height 64 ]
        , Ant.Element.Icons.apiFilled [ width 64, height 64 ]
        , Ant.Element.Icons.appstoreFilled [ width 64, height 64 ]
        , Ant.Element.Icons.audioFilled [ width 64, height 64 ]
        , Ant.Element.Icons.bankFilled [ width 64, height 64 ]
        , Ant.Element.Icons.behanceCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.bellFilled [ width 64, height 64 ]
        , Ant.Element.Icons.bookFilled [ width 64, height 64 ]
        , Ant.Element.Icons.bugFilled [ width 64, height 64 ]
        , Ant.Element.Icons.buildFilled [ width 64, height 64 ]
        , Ant.Element.Icons.bulbFilled [ width 64, height 64 ]
        , Ant.Element.Icons.calculatorFilled [ width 64, height 64 ]
        , Ant.Element.Icons.calendarFilled [ width 64, height 64 ]
        , Ant.Element.Icons.cameraFilled [ width 64, height 64 ]
        , Ant.Element.Icons.carFilled [ width 64, height 64 ]
        , Ant.Element.Icons.carryOutFilled [ width 64, height 64 ]
        , Ant.Element.Icons.ciCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.cloudFilled [ width 64, height 64 ]
        , Ant.Element.Icons.codeFilled [ width 64, height 64 ]
        , Ant.Element.Icons.codeSandboxSquareFilled [ width 64, height 64 ]
        , Ant.Element.Icons.codepenSquareFilled [ width 64, height 64 ]
        , Ant.Element.Icons.compassFilled [ width 64, height 64 ]
        , Ant.Element.Icons.contactsFilled [ width 64, height 64 ]
        , Ant.Element.Icons.containerFilled [ width 64, height 64 ]
        , Ant.Element.Icons.controlFilled [ width 64, height 64 ]
        , Ant.Element.Icons.copyrightCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.creditCardFilled [ width 64, height 64 ]
        , Ant.Element.Icons.crownFilled [ width 64, height 64 ]
        , Ant.Element.Icons.customerServiceFilled [ width 64, height 64 ]
        , Ant.Element.Icons.dashboardFilled [ width 64, height 64 ]
        , Ant.Element.Icons.databaseFilled [ width 64, height 64 ]
        , Ant.Element.Icons.dingtalkCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.dingtalkSquareFilled [ width 64, height 64 ]
        , Ant.Element.Icons.dislikeFilled [ width 64, height 64 ]
        , Ant.Element.Icons.dollarCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.dribbbleCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.dropboxCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.dropboxSquareFilled [ width 64, height 64 ]
        , Ant.Element.Icons.environmentFilled [ width 64, height 64 ]
        , Ant.Element.Icons.euroCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.experimentFilled [ width 64, height 64 ]
        , Ant.Element.Icons.eyeFilled [ width 64, height 64 ]
        , Ant.Element.Icons.eyeInvisibleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.fileAddFilled [ width 64, height 64 ]
        , Ant.Element.Icons.fileExcelFilled [ width 64, height 64 ]
        , Ant.Element.Icons.fileExclamationFilled [ width 64, height 64 ]
        , Ant.Element.Icons.fileFilled [ width 64, height 64 ]
        , Ant.Element.Icons.fileImageFilled [ width 64, height 64 ]
        , Ant.Element.Icons.fileMarkdownFilled [ width 64, height 64 ]
        , Ant.Element.Icons.filePdfFilled [ width 64, height 64 ]
        , Ant.Element.Icons.filePptFilled [ width 64, height 64 ]
        , Ant.Element.Icons.fileTextFilled [ width 64, height 64 ]
        , Ant.Element.Icons.fileUnknownFilled [ width 64, height 64 ]
        , Ant.Element.Icons.fileWordFilled [ width 64, height 64 ]
        , Ant.Element.Icons.fileZipFilled [ width 64, height 64 ]
        , Ant.Element.Icons.filterFilled [ width 64, height 64 ]
        , Ant.Element.Icons.fireFilled [ width 64, height 64 ]
        , Ant.Element.Icons.flagFilled [ width 64, height 64 ]
        , Ant.Element.Icons.folderAddFilled [ width 64, height 64 ]
        , Ant.Element.Icons.folderFilled [ width 64, height 64 ]
        , Ant.Element.Icons.folderOpenFilled [ width 64, height 64 ]
        , Ant.Element.Icons.formatPainterFilled [ width 64, height 64 ]
        , Ant.Element.Icons.frownFilled [ width 64, height 64 ]
        , Ant.Element.Icons.funnelPlotFilled [ width 64, height 64 ]
        , Ant.Element.Icons.giftFilled [ width 64, height 64 ]
        , Ant.Element.Icons.goldFilled [ width 64, height 64 ]
        , Ant.Element.Icons.goldenFilled [ width 64, height 64 ]
        , Ant.Element.Icons.googleCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.googlePlusCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.googlePlusSquareFilled [ width 64, height 64 ]
        , Ant.Element.Icons.googleSquareFilled [ width 64, height 64 ]
        , Ant.Element.Icons.hddFilled [ width 64, height 64 ]
        , Ant.Element.Icons.heartFilled [ width 64, height 64 ]
        , Ant.Element.Icons.homeFilled [ width 64, height 64 ]
        , Ant.Element.Icons.hourglassFilled [ width 64, height 64 ]
        , Ant.Element.Icons.idcardFilled [ width 64, height 64 ]
        , Ant.Element.Icons.ieCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.ieSquareFilled [ width 64, height 64 ]
        , Ant.Element.Icons.insuranceFilled [ width 64, height 64 ]
        , Ant.Element.Icons.interactionFilled [ width 64, height 64 ]
        , Ant.Element.Icons.layoutFilled [ width 64, height 64 ]
        , Ant.Element.Icons.likeFilled [ width 64, height 64 ]
        , Ant.Element.Icons.lockFilled [ width 64, height 64 ]
        , Ant.Element.Icons.macCommandFilled [ width 64, height 64 ]
        , Ant.Element.Icons.mailFilled [ width 64, height 64 ]
        , Ant.Element.Icons.medicineBoxFilled [ width 64, height 64 ]
        , Ant.Element.Icons.mediumCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.mediumSquareFilled [ width 64, height 64 ]
        , Ant.Element.Icons.mehFilled [ width 64, height 64 ]
        , Ant.Element.Icons.messageFilled [ width 64, height 64 ]
        , Ant.Element.Icons.mobileFilled [ width 64, height 64 ]
        , Ant.Element.Icons.moneyCollectFilled [ width 64, height 64 ]
        , Ant.Element.Icons.notificationFilled [ width 64, height 64 ]
        , Ant.Element.Icons.payCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.phoneFilled [ width 64, height 64 ]
        , Ant.Element.Icons.pictureFilled [ width 64, height 64 ]
        , Ant.Element.Icons.playSquareFilled [ width 64, height 64 ]
        , Ant.Element.Icons.poundCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.printerFilled [ width 64, height 64 ]
        , Ant.Element.Icons.profileFilled [ width 64, height 64 ]
        , Ant.Element.Icons.projectFilled [ width 64, height 64 ]
        , Ant.Element.Icons.propertySafetyFilled [ width 64, height 64 ]
        , Ant.Element.Icons.pushpinFilled [ width 64, height 64 ]
        , Ant.Element.Icons.qqCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.qqSquareFilled [ width 64, height 64 ]
        , Ant.Element.Icons.readFilled [ width 64, height 64 ]
        , Ant.Element.Icons.reconciliationFilled [ width 64, height 64 ]
        , Ant.Element.Icons.redEnvelopeFilled [ width 64, height 64 ]
        , Ant.Element.Icons.redditCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.redditSquareFilled [ width 64, height 64 ]
        , Ant.Element.Icons.restFilled [ width 64, height 64 ]
        , Ant.Element.Icons.robotFilled [ width 64, height 64 ]
        , Ant.Element.Icons.rocketFilled [ width 64, height 64 ]
        , Ant.Element.Icons.safetyCertificateFilled [ width 64, height 64 ]
        , Ant.Element.Icons.saveFilled [ width 64, height 64 ]
        , Ant.Element.Icons.scheduleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.securityScanFilled [ width 64, height 64 ]
        , Ant.Element.Icons.settingFilled [ width 64, height 64 ]
        , Ant.Element.Icons.shopFilled [ width 64, height 64 ]
        , Ant.Element.Icons.shoppingFilled [ width 64, height 64 ]
        , Ant.Element.Icons.signalFilled [ width 64, height 64 ]
        , Ant.Element.Icons.sketchCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.sketchSquareFilled [ width 64, height 64 ]
        , Ant.Element.Icons.skinFilled [ width 64, height 64 ]
        , Ant.Element.Icons.slackCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.smileFilled [ width 64, height 64 ]
        , Ant.Element.Icons.soundFilled [ width 64, height 64 ]
        , Ant.Element.Icons.starFilled [ width 64, height 64 ]
        , Ant.Element.Icons.switcherFilled [ width 64, height 64 ]
        , Ant.Element.Icons.tabletFilled [ width 64, height 64 ]
        , Ant.Element.Icons.tagFilled [ width 64, height 64 ]
        , Ant.Element.Icons.tagsFilled [ width 64, height 64 ]
        , Ant.Element.Icons.taobaoSquareFilled [ width 64, height 64 ]
        , Ant.Element.Icons.thunderboltFilled [ width 64, height 64 ]
        , Ant.Element.Icons.toolFilled [ width 64, height 64 ]
        , Ant.Element.Icons.trademarkCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.trophyFilled [ width 64, height 64 ]
        , Ant.Element.Icons.twitterCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.twitterSquareFilled [ width 64, height 64 ]
        , Ant.Element.Icons.unlockFilled [ width 64, height 64 ]
        , Ant.Element.Icons.usbFilled [ width 64, height 64 ]
        , Ant.Element.Icons.videoCameraFilled [ width 64, height 64 ]
        , Ant.Element.Icons.walletFilled [ width 64, height 64 ]
        , Ant.Element.Icons.zhihuCircleFilled [ width 64, height 64 ]
        , Ant.Element.Icons.zhihuSquareFilled [ width 64, height 64 ]
        ]
    , twoTone =
        [ Ant.Element.Icons.accountBookTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.alertTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.apiTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.appstoreTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.audioTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.bankTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.bellTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.bookTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.bugTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.buildTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.bulbTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.calculatorTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.calendarTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.cameraTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.carTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.carryOutTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.ciCircleTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.ciTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.cloudTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.codeTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.compassTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.contactsTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.containerTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.controlTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.copyrightCircleTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.copyrightTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.creditCardTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.crownTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.customerServiceTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.dashboardTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.databaseTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.dislikeTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.dollarCircleTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.dollarTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.environmentTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.euroCircleTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.euroTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.experimentTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.eyeTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.eyeInvisibleTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.fileAddTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.fileExcelTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.fileExclamationTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.fileTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.fileImageTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.fileMarkdownTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.filePdfTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.filePptTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.fileTextTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.fileUnknownTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.fileWordTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.fileZipTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.filterTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.fireTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.flagTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.folderAddTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.folderTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.folderOpenTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.frownTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.funnelPlotTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.giftTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.goldTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.hddTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.heartTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.homeTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.hourglassTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.idcardTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.insuranceTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.interactionTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.layoutTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.likeTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.lockTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.mailTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.medicineBoxTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.mehTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.messageTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.mobileTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.moneyCollectTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.notificationTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.phoneTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.pictureTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.playSquareTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.poundCircleTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.printerTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.profileTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.projectTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.propertySafetyTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.pushpinTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.reconciliationTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.redEnvelopeTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.restTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.rocketTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.safetyCertificateTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.saveTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.scheduleTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.securityScanTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.settingTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.shopTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.shoppingTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.skinTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.smileTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.soundTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.starTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.switcherTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.tabletTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.tagTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.tagsTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.thunderboltTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.toolTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.trademarkCircleTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.trophyTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.unlockTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.usbTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.videoCameraTwoTone [ width 64, height 64 ]
        , Ant.Element.Icons.walletTwoTone [ width 64, height 64 ]
        ]
    }
