-- GENERATE BY ./scripts/generate.ts
-- DO NOT EDIT IT MANUALLY


module Stories exposing (allCategories)

import Ant.Element.Icon exposing (height, width)
import Ant.Element.Icons as Icons
import Element exposing (Element)


type alias Category msg =
    { name : String
    , outlined : List (Element msg)
    , filled : List (Element msg)
    , twoTone : List (Element msg)
    }


allCategories : List (Category msg)
allCategories =
    [ direction
    , suggestion
    , editor
    , data
    , logo
    , other
    ]


direction : Category msg
direction =
    { name = "Directional Icons"
    , outlined =
        [ Icons.stepBackwardOutlined [ width 64, height 64 ]
        , Icons.stepForwardOutlined [ width 64, height 64 ]
        , Icons.fastBackwardOutlined [ width 64, height 64 ]
        , Icons.fastForwardOutlined [ width 64, height 64 ]
        , Icons.shrinkOutlined [ width 64, height 64 ]
        , Icons.arrowsAltOutlined [ width 64, height 64 ]
        , Icons.downOutlined [ width 64, height 64 ]
        , Icons.upOutlined [ width 64, height 64 ]
        , Icons.leftOutlined [ width 64, height 64 ]
        , Icons.rightOutlined [ width 64, height 64 ]
        , Icons.caretUpOutlined [ width 64, height 64 ]
        , Icons.caretDownOutlined [ width 64, height 64 ]
        , Icons.caretLeftOutlined [ width 64, height 64 ]
        , Icons.caretRightOutlined [ width 64, height 64 ]
        , Icons.upCircleOutlined [ width 64, height 64 ]
        , Icons.downCircleOutlined [ width 64, height 64 ]
        , Icons.leftCircleOutlined [ width 64, height 64 ]
        , Icons.rightCircleOutlined [ width 64, height 64 ]
        , Icons.doubleRightOutlined [ width 64, height 64 ]
        , Icons.doubleLeftOutlined [ width 64, height 64 ]
        , Icons.verticalLeftOutlined [ width 64, height 64 ]
        , Icons.verticalRightOutlined [ width 64, height 64 ]
        , Icons.verticalAlignTopOutlined [ width 64, height 64 ]
        , Icons.verticalAlignMiddleOutlined [ width 64, height 64 ]
        , Icons.verticalAlignBottomOutlined [ width 64, height 64 ]
        , Icons.forwardOutlined [ width 64, height 64 ]
        , Icons.backwardOutlined [ width 64, height 64 ]
        , Icons.rollbackOutlined [ width 64, height 64 ]
        , Icons.enterOutlined [ width 64, height 64 ]
        , Icons.retweetOutlined [ width 64, height 64 ]
        , Icons.swapOutlined [ width 64, height 64 ]
        , Icons.swapLeftOutlined [ width 64, height 64 ]
        , Icons.swapRightOutlined [ width 64, height 64 ]
        , Icons.arrowUpOutlined [ width 64, height 64 ]
        , Icons.arrowDownOutlined [ width 64, height 64 ]
        , Icons.arrowLeftOutlined [ width 64, height 64 ]
        , Icons.arrowRightOutlined [ width 64, height 64 ]
        , Icons.playCircleOutlined [ width 64, height 64 ]
        , Icons.upSquareOutlined [ width 64, height 64 ]
        , Icons.downSquareOutlined [ width 64, height 64 ]
        , Icons.leftSquareOutlined [ width 64, height 64 ]
        , Icons.rightSquareOutlined [ width 64, height 64 ]
        , Icons.loginOutlined [ width 64, height 64 ]
        , Icons.logoutOutlined [ width 64, height 64 ]
        , Icons.menuFoldOutlined [ width 64, height 64 ]
        , Icons.menuUnfoldOutlined [ width 64, height 64 ]
        , Icons.borderBottomOutlined [ width 64, height 64 ]
        , Icons.borderHorizontalOutlined [ width 64, height 64 ]
        , Icons.borderInnerOutlined [ width 64, height 64 ]
        , Icons.borderOuterOutlined [ width 64, height 64 ]
        , Icons.borderLeftOutlined [ width 64, height 64 ]
        , Icons.borderRightOutlined [ width 64, height 64 ]
        , Icons.borderTopOutlined [ width 64, height 64 ]
        , Icons.borderVerticleOutlined [ width 64, height 64 ]
        , Icons.picCenterOutlined [ width 64, height 64 ]
        , Icons.picLeftOutlined [ width 64, height 64 ]
        , Icons.picRightOutlined [ width 64, height 64 ]
        , Icons.radiusBottomleftOutlined [ width 64, height 64 ]
        , Icons.radiusBottomrightOutlined [ width 64, height 64 ]
        , Icons.radiusUpleftOutlined [ width 64, height 64 ]
        , Icons.radiusUprightOutlined [ width 64, height 64 ]
        , Icons.fullscreenOutlined [ width 64, height 64 ]
        , Icons.fullscreenExitOutlined [ width 64, height 64 ]
        ]
    , filled =
        [ Icons.stepBackwardFilled [ width 64, height 64 ]
        , Icons.stepForwardFilled [ width 64, height 64 ]
        , Icons.fastBackwardFilled [ width 64, height 64 ]
        , Icons.fastForwardFilled [ width 64, height 64 ]
        , Icons.caretUpFilled [ width 64, height 64 ]
        , Icons.caretDownFilled [ width 64, height 64 ]
        , Icons.caretLeftFilled [ width 64, height 64 ]
        , Icons.caretRightFilled [ width 64, height 64 ]
        , Icons.upCircleFilled [ width 64, height 64 ]
        , Icons.downCircleFilled [ width 64, height 64 ]
        , Icons.leftCircleFilled [ width 64, height 64 ]
        , Icons.rightCircleFilled [ width 64, height 64 ]
        , Icons.forwardFilled [ width 64, height 64 ]
        , Icons.backwardFilled [ width 64, height 64 ]
        , Icons.playCircleFilled [ width 64, height 64 ]
        , Icons.upSquareFilled [ width 64, height 64 ]
        , Icons.downSquareFilled [ width 64, height 64 ]
        , Icons.leftSquareFilled [ width 64, height 64 ]
        , Icons.rightSquareFilled [ width 64, height 64 ]
        ]
    , twoTone =
        [ Icons.upCircleTwoTone [ width 64, height 64 ]
        , Icons.downCircleTwoTone [ width 64, height 64 ]
        , Icons.leftCircleTwoTone [ width 64, height 64 ]
        , Icons.rightCircleTwoTone [ width 64, height 64 ]
        , Icons.playCircleTwoTone [ width 64, height 64 ]
        , Icons.upSquareTwoTone [ width 64, height 64 ]
        , Icons.downSquareTwoTone [ width 64, height 64 ]
        , Icons.leftSquareTwoTone [ width 64, height 64 ]
        , Icons.rightSquareTwoTone [ width 64, height 64 ]
        ]
    }


suggestion : Category msg
suggestion =
    { name = "Suggested Icons"
    , outlined =
        [ Icons.questionOutlined [ width 64, height 64 ]
        , Icons.questionCircleOutlined [ width 64, height 64 ]
        , Icons.plusOutlined [ width 64, height 64 ]
        , Icons.plusCircleOutlined [ width 64, height 64 ]
        , Icons.pauseOutlined [ width 64, height 64 ]
        , Icons.pauseCircleOutlined [ width 64, height 64 ]
        , Icons.minusOutlined [ width 64, height 64 ]
        , Icons.minusCircleOutlined [ width 64, height 64 ]
        , Icons.plusSquareOutlined [ width 64, height 64 ]
        , Icons.minusSquareOutlined [ width 64, height 64 ]
        , Icons.infoOutlined [ width 64, height 64 ]
        , Icons.infoCircleOutlined [ width 64, height 64 ]
        , Icons.exclamationOutlined [ width 64, height 64 ]
        , Icons.exclamationCircleOutlined [ width 64, height 64 ]
        , Icons.closeOutlined [ width 64, height 64 ]
        , Icons.closeCircleOutlined [ width 64, height 64 ]
        , Icons.closeSquareOutlined [ width 64, height 64 ]
        , Icons.checkOutlined [ width 64, height 64 ]
        , Icons.checkCircleOutlined [ width 64, height 64 ]
        , Icons.checkSquareOutlined [ width 64, height 64 ]
        , Icons.clockCircleOutlined [ width 64, height 64 ]
        , Icons.warningOutlined [ width 64, height 64 ]
        , Icons.issuesCloseOutlined [ width 64, height 64 ]
        , Icons.stopOutlined [ width 64, height 64 ]
        ]
    , filled =
        [ Icons.questionCircleFilled [ width 64, height 64 ]
        , Icons.plusCircleFilled [ width 64, height 64 ]
        , Icons.pauseCircleFilled [ width 64, height 64 ]
        , Icons.minusCircleFilled [ width 64, height 64 ]
        , Icons.plusSquareFilled [ width 64, height 64 ]
        , Icons.minusSquareFilled [ width 64, height 64 ]
        , Icons.infoCircleFilled [ width 64, height 64 ]
        , Icons.exclamationCircleFilled [ width 64, height 64 ]
        , Icons.closeCircleFilled [ width 64, height 64 ]
        , Icons.closeSquareFilled [ width 64, height 64 ]
        , Icons.checkCircleFilled [ width 64, height 64 ]
        , Icons.checkSquareFilled [ width 64, height 64 ]
        , Icons.clockCircleFilled [ width 64, height 64 ]
        , Icons.warningFilled [ width 64, height 64 ]
        , Icons.stopFilled [ width 64, height 64 ]
        ]
    , twoTone =
        [ Icons.questionCircleTwoTone [ width 64, height 64 ]
        , Icons.plusCircleTwoTone [ width 64, height 64 ]
        , Icons.pauseCircleTwoTone [ width 64, height 64 ]
        , Icons.minusCircleTwoTone [ width 64, height 64 ]
        , Icons.plusSquareTwoTone [ width 64, height 64 ]
        , Icons.minusSquareTwoTone [ width 64, height 64 ]
        , Icons.infoCircleTwoTone [ width 64, height 64 ]
        , Icons.exclamationCircleTwoTone [ width 64, height 64 ]
        , Icons.closeCircleTwoTone [ width 64, height 64 ]
        , Icons.closeSquareTwoTone [ width 64, height 64 ]
        , Icons.checkCircleTwoTone [ width 64, height 64 ]
        , Icons.checkSquareTwoTone [ width 64, height 64 ]
        , Icons.clockCircleTwoTone [ width 64, height 64 ]
        , Icons.warningTwoTone [ width 64, height 64 ]
        , Icons.stopTwoTone [ width 64, height 64 ]
        ]
    }


editor : Category msg
editor =
    { name = "Editor Icons"
    , outlined =
        [ Icons.editOutlined [ width 64, height 64 ]
        , Icons.formOutlined [ width 64, height 64 ]
        , Icons.copyOutlined [ width 64, height 64 ]
        , Icons.scissorOutlined [ width 64, height 64 ]
        , Icons.deleteOutlined [ width 64, height 64 ]
        , Icons.snippetsOutlined [ width 64, height 64 ]
        , Icons.diffOutlined [ width 64, height 64 ]
        , Icons.highlightOutlined [ width 64, height 64 ]
        , Icons.alignCenterOutlined [ width 64, height 64 ]
        , Icons.alignLeftOutlined [ width 64, height 64 ]
        , Icons.alignRightOutlined [ width 64, height 64 ]
        , Icons.bgColorsOutlined [ width 64, height 64 ]
        , Icons.boldOutlined [ width 64, height 64 ]
        , Icons.italicOutlined [ width 64, height 64 ]
        , Icons.underlineOutlined [ width 64, height 64 ]
        , Icons.strikethroughOutlined [ width 64, height 64 ]
        , Icons.redoOutlined [ width 64, height 64 ]
        , Icons.undoOutlined [ width 64, height 64 ]
        , Icons.zoomInOutlined [ width 64, height 64 ]
        , Icons.zoomOutOutlined [ width 64, height 64 ]
        , Icons.fontColorsOutlined [ width 64, height 64 ]
        , Icons.fontSizeOutlined [ width 64, height 64 ]
        , Icons.lineHeightOutlined [ width 64, height 64 ]
        , Icons.dashOutlined [ width 64, height 64 ]
        , Icons.smallDashOutlined [ width 64, height 64 ]
        , Icons.sortAscendingOutlined [ width 64, height 64 ]
        , Icons.sortDescendingOutlined [ width 64, height 64 ]
        , Icons.dragOutlined [ width 64, height 64 ]
        , Icons.orderedListOutlined [ width 64, height 64 ]
        , Icons.unorderedListOutlined [ width 64, height 64 ]
        , Icons.radiusSettingOutlined [ width 64, height 64 ]
        , Icons.columnWidthOutlined [ width 64, height 64 ]
        , Icons.columnHeightOutlined [ width 64, height 64 ]
        ]
    , filled =
        [ Icons.editFilled [ width 64, height 64 ]
        , Icons.copyFilled [ width 64, height 64 ]
        , Icons.deleteFilled [ width 64, height 64 ]
        , Icons.snippetsFilled [ width 64, height 64 ]
        , Icons.diffFilled [ width 64, height 64 ]
        , Icons.highlightFilled [ width 64, height 64 ]
        ]
    , twoTone =
        [ Icons.editTwoTone [ width 64, height 64 ]
        , Icons.copyTwoTone [ width 64, height 64 ]
        , Icons.deleteTwoTone [ width 64, height 64 ]
        , Icons.snippetsTwoTone [ width 64, height 64 ]
        , Icons.diffTwoTone [ width 64, height 64 ]
        , Icons.highlightTwoTone [ width 64, height 64 ]
        ]
    }


data : Category msg
data =
    { name = "Data Icons"
    , outlined =
        [ Icons.areaChartOutlined [ width 64, height 64 ]
        , Icons.pieChartOutlined [ width 64, height 64 ]
        , Icons.barChartOutlined [ width 64, height 64 ]
        , Icons.dotChartOutlined [ width 64, height 64 ]
        , Icons.lineChartOutlined [ width 64, height 64 ]
        , Icons.radarChartOutlined [ width 64, height 64 ]
        , Icons.heatMapOutlined [ width 64, height 64 ]
        , Icons.fallOutlined [ width 64, height 64 ]
        , Icons.riseOutlined [ width 64, height 64 ]
        , Icons.stockOutlined [ width 64, height 64 ]
        , Icons.boxPlotOutlined [ width 64, height 64 ]
        , Icons.fundOutlined [ width 64, height 64 ]
        , Icons.slidersOutlined [ width 64, height 64 ]
        ]
    , filled =
        [ Icons.pieChartFilled [ width 64, height 64 ]
        , Icons.boxPlotFilled [ width 64, height 64 ]
        , Icons.fundFilled [ width 64, height 64 ]
        , Icons.slidersFilled [ width 64, height 64 ]
        ]
    , twoTone =
        [ Icons.pieChartTwoTone [ width 64, height 64 ]
        , Icons.boxPlotTwoTone [ width 64, height 64 ]
        , Icons.fundTwoTone [ width 64, height 64 ]
        , Icons.slidersTwoTone [ width 64, height 64 ]
        ]
    }


logo : Category msg
logo =
    { name = "Brand and Logos"
    , outlined =
        [ Icons.androidOutlined [ width 64, height 64 ]
        , Icons.appleOutlined [ width 64, height 64 ]
        , Icons.windowsOutlined [ width 64, height 64 ]
        , Icons.ieOutlined [ width 64, height 64 ]
        , Icons.chromeOutlined [ width 64, height 64 ]
        , Icons.githubOutlined [ width 64, height 64 ]
        , Icons.aliwangwangOutlined [ width 64, height 64 ]
        , Icons.dingdingOutlined [ width 64, height 64 ]
        , Icons.weiboSquareOutlined [ width 64, height 64 ]
        , Icons.weiboCircleOutlined [ width 64, height 64 ]
        , Icons.taobaoCircleOutlined [ width 64, height 64 ]
        , Icons.html5Outlined [ width 64, height 64 ]
        , Icons.weiboOutlined [ width 64, height 64 ]
        , Icons.twitterOutlined [ width 64, height 64 ]
        , Icons.wechatOutlined [ width 64, height 64 ]
        , Icons.youtubeOutlined [ width 64, height 64 ]
        , Icons.alipayCircleOutlined [ width 64, height 64 ]
        , Icons.taobaoOutlined [ width 64, height 64 ]
        , Icons.skypeOutlined [ width 64, height 64 ]
        , Icons.qqOutlined [ width 64, height 64 ]
        , Icons.mediumWorkmarkOutlined [ width 64, height 64 ]
        , Icons.gitlabOutlined [ width 64, height 64 ]
        , Icons.mediumOutlined [ width 64, height 64 ]
        , Icons.linkedinOutlined [ width 64, height 64 ]
        , Icons.googlePlusOutlined [ width 64, height 64 ]
        , Icons.dropboxOutlined [ width 64, height 64 ]
        , Icons.facebookOutlined [ width 64, height 64 ]
        , Icons.codepenOutlined [ width 64, height 64 ]
        , Icons.codeSandboxOutlined [ width 64, height 64 ]
        , Icons.amazonOutlined [ width 64, height 64 ]
        , Icons.googleOutlined [ width 64, height 64 ]
        , Icons.codepenCircleOutlined [ width 64, height 64 ]
        , Icons.alipayOutlined [ width 64, height 64 ]
        , Icons.antDesignOutlined [ width 64, height 64 ]
        , Icons.antCloudOutlined [ width 64, height 64 ]
        , Icons.aliyunOutlined [ width 64, height 64 ]
        , Icons.zhihuOutlined [ width 64, height 64 ]
        , Icons.slackOutlined [ width 64, height 64 ]
        , Icons.slackSquareOutlined [ width 64, height 64 ]
        , Icons.behanceOutlined [ width 64, height 64 ]
        , Icons.behanceSquareOutlined [ width 64, height 64 ]
        , Icons.dribbbleOutlined [ width 64, height 64 ]
        , Icons.dribbbleSquareOutlined [ width 64, height 64 ]
        , Icons.instagramOutlined [ width 64, height 64 ]
        , Icons.yuqueOutlined [ width 64, height 64 ]
        , Icons.alibabaOutlined [ width 64, height 64 ]
        , Icons.yahooOutlined [ width 64, height 64 ]
        , Icons.redditOutlined [ width 64, height 64 ]
        , Icons.sketchOutlined [ width 64, height 64 ]
        ]
    , filled =
        [ Icons.androidFilled [ width 64, height 64 ]
        , Icons.appleFilled [ width 64, height 64 ]
        , Icons.windowsFilled [ width 64, height 64 ]
        , Icons.chromeFilled [ width 64, height 64 ]
        , Icons.githubFilled [ width 64, height 64 ]
        , Icons.aliwangwangFilled [ width 64, height 64 ]
        , Icons.weiboSquareFilled [ width 64, height 64 ]
        , Icons.weiboCircleFilled [ width 64, height 64 ]
        , Icons.taobaoCircleFilled [ width 64, height 64 ]
        , Icons.html5Filled [ width 64, height 64 ]
        , Icons.wechatFilled [ width 64, height 64 ]
        , Icons.youtubeFilled [ width 64, height 64 ]
        , Icons.alipayCircleFilled [ width 64, height 64 ]
        , Icons.skypeFilled [ width 64, height 64 ]
        , Icons.gitlabFilled [ width 64, height 64 ]
        , Icons.linkedinFilled [ width 64, height 64 ]
        , Icons.facebookFilled [ width 64, height 64 ]
        , Icons.codeSandboxCircleFilled [ width 64, height 64 ]
        , Icons.codepenCircleFilled [ width 64, height 64 ]
        , Icons.slackSquareFilled [ width 64, height 64 ]
        , Icons.behanceSquareFilled [ width 64, height 64 ]
        , Icons.dribbbleSquareFilled [ width 64, height 64 ]
        , Icons.instagramFilled [ width 64, height 64 ]
        , Icons.yuqueFilled [ width 64, height 64 ]
        , Icons.yahooFilled [ width 64, height 64 ]
        ]
    , twoTone =
        [ Icons.html5TwoTone [ width 64, height 64 ]
        ]
    }


other : Category msg
other =
    { name = "Application Icons"
    , outlined =
        [ Icons.accountBookOutlined [ width 64, height 64 ]
        , Icons.aimOutlined [ width 64, height 64 ]
        , Icons.alertOutlined [ width 64, height 64 ]
        , Icons.apartmentOutlined [ width 64, height 64 ]
        , Icons.apiOutlined [ width 64, height 64 ]
        , Icons.appstoreAddOutlined [ width 64, height 64 ]
        , Icons.appstoreOutlined [ width 64, height 64 ]
        , Icons.audioOutlined [ width 64, height 64 ]
        , Icons.audioMutedOutlined [ width 64, height 64 ]
        , Icons.auditOutlined [ width 64, height 64 ]
        , Icons.bankOutlined [ width 64, height 64 ]
        , Icons.barcodeOutlined [ width 64, height 64 ]
        , Icons.barsOutlined [ width 64, height 64 ]
        , Icons.bellOutlined [ width 64, height 64 ]
        , Icons.blockOutlined [ width 64, height 64 ]
        , Icons.bookOutlined [ width 64, height 64 ]
        , Icons.borderOutlined [ width 64, height 64 ]
        , Icons.borderlessTableOutlined [ width 64, height 64 ]
        , Icons.branchesOutlined [ width 64, height 64 ]
        , Icons.bugOutlined [ width 64, height 64 ]
        , Icons.buildOutlined [ width 64, height 64 ]
        , Icons.bulbOutlined [ width 64, height 64 ]
        , Icons.calculatorOutlined [ width 64, height 64 ]
        , Icons.calendarOutlined [ width 64, height 64 ]
        , Icons.cameraOutlined [ width 64, height 64 ]
        , Icons.carOutlined [ width 64, height 64 ]
        , Icons.carryOutOutlined [ width 64, height 64 ]
        , Icons.ciCircleOutlined [ width 64, height 64 ]
        , Icons.ciOutlined [ width 64, height 64 ]
        , Icons.clearOutlined [ width 64, height 64 ]
        , Icons.cloudDownloadOutlined [ width 64, height 64 ]
        , Icons.cloudOutlined [ width 64, height 64 ]
        , Icons.cloudServerOutlined [ width 64, height 64 ]
        , Icons.cloudSyncOutlined [ width 64, height 64 ]
        , Icons.cloudUploadOutlined [ width 64, height 64 ]
        , Icons.clusterOutlined [ width 64, height 64 ]
        , Icons.codeOutlined [ width 64, height 64 ]
        , Icons.coffeeOutlined [ width 64, height 64 ]
        , Icons.commentOutlined [ width 64, height 64 ]
        , Icons.compassOutlined [ width 64, height 64 ]
        , Icons.compressOutlined [ width 64, height 64 ]
        , Icons.consoleSqlOutlined [ width 64, height 64 ]
        , Icons.contactsOutlined [ width 64, height 64 ]
        , Icons.containerOutlined [ width 64, height 64 ]
        , Icons.controlOutlined [ width 64, height 64 ]
        , Icons.copyrightCircleOutlined [ width 64, height 64 ]
        , Icons.copyrightOutlined [ width 64, height 64 ]
        , Icons.creditCardOutlined [ width 64, height 64 ]
        , Icons.crownOutlined [ width 64, height 64 ]
        , Icons.customerServiceOutlined [ width 64, height 64 ]
        , Icons.dashboardOutlined [ width 64, height 64 ]
        , Icons.databaseOutlined [ width 64, height 64 ]
        , Icons.deleteColumnOutlined [ width 64, height 64 ]
        , Icons.deleteRowOutlined [ width 64, height 64 ]
        , Icons.deliveredProcedureOutlined [ width 64, height 64 ]
        , Icons.deploymentUnitOutlined [ width 64, height 64 ]
        , Icons.desktopOutlined [ width 64, height 64 ]
        , Icons.dingtalkOutlined [ width 64, height 64 ]
        , Icons.disconnectOutlined [ width 64, height 64 ]
        , Icons.dislikeOutlined [ width 64, height 64 ]
        , Icons.dollarCircleOutlined [ width 64, height 64 ]
        , Icons.dollarOutlined [ width 64, height 64 ]
        , Icons.downloadOutlined [ width 64, height 64 ]
        , Icons.ellipsisOutlined [ width 64, height 64 ]
        , Icons.environmentOutlined [ width 64, height 64 ]
        , Icons.euroCircleOutlined [ width 64, height 64 ]
        , Icons.euroOutlined [ width 64, height 64 ]
        , Icons.exceptionOutlined [ width 64, height 64 ]
        , Icons.expandAltOutlined [ width 64, height 64 ]
        , Icons.expandOutlined [ width 64, height 64 ]
        , Icons.experimentOutlined [ width 64, height 64 ]
        , Icons.exportOutlined [ width 64, height 64 ]
        , Icons.eyeOutlined [ width 64, height 64 ]
        , Icons.eyeInvisibleOutlined [ width 64, height 64 ]
        , Icons.fieldBinaryOutlined [ width 64, height 64 ]
        , Icons.fieldNumberOutlined [ width 64, height 64 ]
        , Icons.fieldStringOutlined [ width 64, height 64 ]
        , Icons.fieldTimeOutlined [ width 64, height 64 ]
        , Icons.fileAddOutlined [ width 64, height 64 ]
        , Icons.fileDoneOutlined [ width 64, height 64 ]
        , Icons.fileExcelOutlined [ width 64, height 64 ]
        , Icons.fileExclamationOutlined [ width 64, height 64 ]
        , Icons.fileOutlined [ width 64, height 64 ]
        , Icons.fileGifOutlined [ width 64, height 64 ]
        , Icons.fileImageOutlined [ width 64, height 64 ]
        , Icons.fileJpgOutlined [ width 64, height 64 ]
        , Icons.fileMarkdownOutlined [ width 64, height 64 ]
        , Icons.filePdfOutlined [ width 64, height 64 ]
        , Icons.filePptOutlined [ width 64, height 64 ]
        , Icons.fileProtectOutlined [ width 64, height 64 ]
        , Icons.fileSearchOutlined [ width 64, height 64 ]
        , Icons.fileSyncOutlined [ width 64, height 64 ]
        , Icons.fileTextOutlined [ width 64, height 64 ]
        , Icons.fileUnknownOutlined [ width 64, height 64 ]
        , Icons.fileWordOutlined [ width 64, height 64 ]
        , Icons.fileZipOutlined [ width 64, height 64 ]
        , Icons.filterOutlined [ width 64, height 64 ]
        , Icons.fireOutlined [ width 64, height 64 ]
        , Icons.flagOutlined [ width 64, height 64 ]
        , Icons.folderAddOutlined [ width 64, height 64 ]
        , Icons.folderOutlined [ width 64, height 64 ]
        , Icons.folderOpenOutlined [ width 64, height 64 ]
        , Icons.folderViewOutlined [ width 64, height 64 ]
        , Icons.forkOutlined [ width 64, height 64 ]
        , Icons.formatPainterOutlined [ width 64, height 64 ]
        , Icons.frownOutlined [ width 64, height 64 ]
        , Icons.functionOutlined [ width 64, height 64 ]
        , Icons.fundProjectionScreenOutlined [ width 64, height 64 ]
        , Icons.fundViewOutlined [ width 64, height 64 ]
        , Icons.funnelPlotOutlined [ width 64, height 64 ]
        , Icons.gatewayOutlined [ width 64, height 64 ]
        , Icons.gifOutlined [ width 64, height 64 ]
        , Icons.giftOutlined [ width 64, height 64 ]
        , Icons.globalOutlined [ width 64, height 64 ]
        , Icons.goldOutlined [ width 64, height 64 ]
        , Icons.groupOutlined [ width 64, height 64 ]
        , Icons.hddOutlined [ width 64, height 64 ]
        , Icons.heartOutlined [ width 64, height 64 ]
        , Icons.historyOutlined [ width 64, height 64 ]
        , Icons.homeOutlined [ width 64, height 64 ]
        , Icons.hourglassOutlined [ width 64, height 64 ]
        , Icons.idcardOutlined [ width 64, height 64 ]
        , Icons.importOutlined [ width 64, height 64 ]
        , Icons.inboxOutlined [ width 64, height 64 ]
        , Icons.insertRowAboveOutlined [ width 64, height 64 ]
        , Icons.insertRowBelowOutlined [ width 64, height 64 ]
        , Icons.insertRowLeftOutlined [ width 64, height 64 ]
        , Icons.insertRowRightOutlined [ width 64, height 64 ]
        , Icons.insuranceOutlined [ width 64, height 64 ]
        , Icons.interactionOutlined [ width 64, height 64 ]
        , Icons.keyOutlined [ width 64, height 64 ]
        , Icons.laptopOutlined [ width 64, height 64 ]
        , Icons.layoutOutlined [ width 64, height 64 ]
        , Icons.likeOutlined [ width 64, height 64 ]
        , Icons.lineOutlined [ width 64, height 64 ]
        , Icons.linkOutlined [ width 64, height 64 ]
        , Icons.loading3QuartersOutlined [ width 64, height 64 ]
        , Icons.loadingOutlined [ width 64, height 64 ]
        , Icons.lockOutlined [ width 64, height 64 ]
        , Icons.macCommandOutlined [ width 64, height 64 ]
        , Icons.mailOutlined [ width 64, height 64 ]
        , Icons.manOutlined [ width 64, height 64 ]
        , Icons.medicineBoxOutlined [ width 64, height 64 ]
        , Icons.mehOutlined [ width 64, height 64 ]
        , Icons.menuOutlined [ width 64, height 64 ]
        , Icons.mergeCellsOutlined [ width 64, height 64 ]
        , Icons.messageOutlined [ width 64, height 64 ]
        , Icons.mobileOutlined [ width 64, height 64 ]
        , Icons.moneyCollectOutlined [ width 64, height 64 ]
        , Icons.monitorOutlined [ width 64, height 64 ]
        , Icons.moreOutlined [ width 64, height 64 ]
        , Icons.nodeCollapseOutlined [ width 64, height 64 ]
        , Icons.nodeExpandOutlined [ width 64, height 64 ]
        , Icons.nodeIndexOutlined [ width 64, height 64 ]
        , Icons.notificationOutlined [ width 64, height 64 ]
        , Icons.numberOutlined [ width 64, height 64 ]
        , Icons.oneToOneOutlined [ width 64, height 64 ]
        , Icons.paperClipOutlined [ width 64, height 64 ]
        , Icons.partitionOutlined [ width 64, height 64 ]
        , Icons.payCircleOutlined [ width 64, height 64 ]
        , Icons.percentageOutlined [ width 64, height 64 ]
        , Icons.phoneOutlined [ width 64, height 64 ]
        , Icons.pictureOutlined [ width 64, height 64 ]
        , Icons.playSquareOutlined [ width 64, height 64 ]
        , Icons.poundCircleOutlined [ width 64, height 64 ]
        , Icons.poundOutlined [ width 64, height 64 ]
        , Icons.poweroffOutlined [ width 64, height 64 ]
        , Icons.printerOutlined [ width 64, height 64 ]
        , Icons.profileOutlined [ width 64, height 64 ]
        , Icons.projectOutlined [ width 64, height 64 ]
        , Icons.propertySafetyOutlined [ width 64, height 64 ]
        , Icons.pullRequestOutlined [ width 64, height 64 ]
        , Icons.pushpinOutlined [ width 64, height 64 ]
        , Icons.qrcodeOutlined [ width 64, height 64 ]
        , Icons.readOutlined [ width 64, height 64 ]
        , Icons.reconciliationOutlined [ width 64, height 64 ]
        , Icons.redEnvelopeOutlined [ width 64, height 64 ]
        , Icons.reloadOutlined [ width 64, height 64 ]
        , Icons.restOutlined [ width 64, height 64 ]
        , Icons.robotOutlined [ width 64, height 64 ]
        , Icons.rocketOutlined [ width 64, height 64 ]
        , Icons.rotateLeftOutlined [ width 64, height 64 ]
        , Icons.rotateRightOutlined [ width 64, height 64 ]
        , Icons.safetyCertificateOutlined [ width 64, height 64 ]
        , Icons.safetyOutlined [ width 64, height 64 ]
        , Icons.saveOutlined [ width 64, height 64 ]
        , Icons.scanOutlined [ width 64, height 64 ]
        , Icons.scheduleOutlined [ width 64, height 64 ]
        , Icons.searchOutlined [ width 64, height 64 ]
        , Icons.securityScanOutlined [ width 64, height 64 ]
        , Icons.selectOutlined [ width 64, height 64 ]
        , Icons.sendOutlined [ width 64, height 64 ]
        , Icons.settingOutlined [ width 64, height 64 ]
        , Icons.shakeOutlined [ width 64, height 64 ]
        , Icons.shareAltOutlined [ width 64, height 64 ]
        , Icons.shopOutlined [ width 64, height 64 ]
        , Icons.shoppingCartOutlined [ width 64, height 64 ]
        , Icons.shoppingOutlined [ width 64, height 64 ]
        , Icons.sisternodeOutlined [ width 64, height 64 ]
        , Icons.skinOutlined [ width 64, height 64 ]
        , Icons.smileOutlined [ width 64, height 64 ]
        , Icons.solutionOutlined [ width 64, height 64 ]
        , Icons.soundOutlined [ width 64, height 64 ]
        , Icons.splitCellsOutlined [ width 64, height 64 ]
        , Icons.starOutlined [ width 64, height 64 ]
        , Icons.subnodeOutlined [ width 64, height 64 ]
        , Icons.switcherOutlined [ width 64, height 64 ]
        , Icons.syncOutlined [ width 64, height 64 ]
        , Icons.tableOutlined [ width 64, height 64 ]
        , Icons.tabletOutlined [ width 64, height 64 ]
        , Icons.tagOutlined [ width 64, height 64 ]
        , Icons.tagsOutlined [ width 64, height 64 ]
        , Icons.teamOutlined [ width 64, height 64 ]
        , Icons.thunderboltOutlined [ width 64, height 64 ]
        , Icons.toTopOutlined [ width 64, height 64 ]
        , Icons.toolOutlined [ width 64, height 64 ]
        , Icons.trademarkCircleOutlined [ width 64, height 64 ]
        , Icons.trademarkOutlined [ width 64, height 64 ]
        , Icons.transactionOutlined [ width 64, height 64 ]
        , Icons.translationOutlined [ width 64, height 64 ]
        , Icons.trophyOutlined [ width 64, height 64 ]
        , Icons.ungroupOutlined [ width 64, height 64 ]
        , Icons.unlockOutlined [ width 64, height 64 ]
        , Icons.uploadOutlined [ width 64, height 64 ]
        , Icons.usbOutlined [ width 64, height 64 ]
        , Icons.userAddOutlined [ width 64, height 64 ]
        , Icons.userDeleteOutlined [ width 64, height 64 ]
        , Icons.userOutlined [ width 64, height 64 ]
        , Icons.userSwitchOutlined [ width 64, height 64 ]
        , Icons.usergroupAddOutlined [ width 64, height 64 ]
        , Icons.usergroupDeleteOutlined [ width 64, height 64 ]
        , Icons.verifiedOutlined [ width 64, height 64 ]
        , Icons.videoCameraAddOutlined [ width 64, height 64 ]
        , Icons.videoCameraOutlined [ width 64, height 64 ]
        , Icons.walletOutlined [ width 64, height 64 ]
        , Icons.whatsAppOutlined [ width 64, height 64 ]
        , Icons.wifiOutlined [ width 64, height 64 ]
        , Icons.womanOutlined [ width 64, height 64 ]
        ]
    , filled =
        [ Icons.accountBookFilled [ width 64, height 64 ]
        , Icons.alertFilled [ width 64, height 64 ]
        , Icons.alipaySquareFilled [ width 64, height 64 ]
        , Icons.amazonCircleFilled [ width 64, height 64 ]
        , Icons.amazonSquareFilled [ width 64, height 64 ]
        , Icons.apiFilled [ width 64, height 64 ]
        , Icons.appstoreFilled [ width 64, height 64 ]
        , Icons.audioFilled [ width 64, height 64 ]
        , Icons.bankFilled [ width 64, height 64 ]
        , Icons.behanceCircleFilled [ width 64, height 64 ]
        , Icons.bellFilled [ width 64, height 64 ]
        , Icons.bookFilled [ width 64, height 64 ]
        , Icons.bugFilled [ width 64, height 64 ]
        , Icons.buildFilled [ width 64, height 64 ]
        , Icons.bulbFilled [ width 64, height 64 ]
        , Icons.calculatorFilled [ width 64, height 64 ]
        , Icons.calendarFilled [ width 64, height 64 ]
        , Icons.cameraFilled [ width 64, height 64 ]
        , Icons.carFilled [ width 64, height 64 ]
        , Icons.carryOutFilled [ width 64, height 64 ]
        , Icons.ciCircleFilled [ width 64, height 64 ]
        , Icons.cloudFilled [ width 64, height 64 ]
        , Icons.codeFilled [ width 64, height 64 ]
        , Icons.codeSandboxSquareFilled [ width 64, height 64 ]
        , Icons.codepenSquareFilled [ width 64, height 64 ]
        , Icons.compassFilled [ width 64, height 64 ]
        , Icons.contactsFilled [ width 64, height 64 ]
        , Icons.containerFilled [ width 64, height 64 ]
        , Icons.controlFilled [ width 64, height 64 ]
        , Icons.copyrightCircleFilled [ width 64, height 64 ]
        , Icons.creditCardFilled [ width 64, height 64 ]
        , Icons.crownFilled [ width 64, height 64 ]
        , Icons.customerServiceFilled [ width 64, height 64 ]
        , Icons.dashboardFilled [ width 64, height 64 ]
        , Icons.databaseFilled [ width 64, height 64 ]
        , Icons.dingtalkCircleFilled [ width 64, height 64 ]
        , Icons.dingtalkSquareFilled [ width 64, height 64 ]
        , Icons.dislikeFilled [ width 64, height 64 ]
        , Icons.dollarCircleFilled [ width 64, height 64 ]
        , Icons.dribbbleCircleFilled [ width 64, height 64 ]
        , Icons.dropboxCircleFilled [ width 64, height 64 ]
        , Icons.dropboxSquareFilled [ width 64, height 64 ]
        , Icons.environmentFilled [ width 64, height 64 ]
        , Icons.euroCircleFilled [ width 64, height 64 ]
        , Icons.experimentFilled [ width 64, height 64 ]
        , Icons.eyeFilled [ width 64, height 64 ]
        , Icons.eyeInvisibleFilled [ width 64, height 64 ]
        , Icons.fileAddFilled [ width 64, height 64 ]
        , Icons.fileExcelFilled [ width 64, height 64 ]
        , Icons.fileExclamationFilled [ width 64, height 64 ]
        , Icons.fileFilled [ width 64, height 64 ]
        , Icons.fileImageFilled [ width 64, height 64 ]
        , Icons.fileMarkdownFilled [ width 64, height 64 ]
        , Icons.filePdfFilled [ width 64, height 64 ]
        , Icons.filePptFilled [ width 64, height 64 ]
        , Icons.fileTextFilled [ width 64, height 64 ]
        , Icons.fileUnknownFilled [ width 64, height 64 ]
        , Icons.fileWordFilled [ width 64, height 64 ]
        , Icons.fileZipFilled [ width 64, height 64 ]
        , Icons.filterFilled [ width 64, height 64 ]
        , Icons.fireFilled [ width 64, height 64 ]
        , Icons.flagFilled [ width 64, height 64 ]
        , Icons.folderAddFilled [ width 64, height 64 ]
        , Icons.folderFilled [ width 64, height 64 ]
        , Icons.folderOpenFilled [ width 64, height 64 ]
        , Icons.formatPainterFilled [ width 64, height 64 ]
        , Icons.frownFilled [ width 64, height 64 ]
        , Icons.funnelPlotFilled [ width 64, height 64 ]
        , Icons.giftFilled [ width 64, height 64 ]
        , Icons.goldFilled [ width 64, height 64 ]
        , Icons.goldenFilled [ width 64, height 64 ]
        , Icons.googleCircleFilled [ width 64, height 64 ]
        , Icons.googlePlusCircleFilled [ width 64, height 64 ]
        , Icons.googlePlusSquareFilled [ width 64, height 64 ]
        , Icons.googleSquareFilled [ width 64, height 64 ]
        , Icons.hddFilled [ width 64, height 64 ]
        , Icons.heartFilled [ width 64, height 64 ]
        , Icons.homeFilled [ width 64, height 64 ]
        , Icons.hourglassFilled [ width 64, height 64 ]
        , Icons.idcardFilled [ width 64, height 64 ]
        , Icons.ieCircleFilled [ width 64, height 64 ]
        , Icons.ieSquareFilled [ width 64, height 64 ]
        , Icons.insuranceFilled [ width 64, height 64 ]
        , Icons.interactionFilled [ width 64, height 64 ]
        , Icons.layoutFilled [ width 64, height 64 ]
        , Icons.likeFilled [ width 64, height 64 ]
        , Icons.lockFilled [ width 64, height 64 ]
        , Icons.macCommandFilled [ width 64, height 64 ]
        , Icons.mailFilled [ width 64, height 64 ]
        , Icons.medicineBoxFilled [ width 64, height 64 ]
        , Icons.mediumCircleFilled [ width 64, height 64 ]
        , Icons.mediumSquareFilled [ width 64, height 64 ]
        , Icons.mehFilled [ width 64, height 64 ]
        , Icons.messageFilled [ width 64, height 64 ]
        , Icons.mobileFilled [ width 64, height 64 ]
        , Icons.moneyCollectFilled [ width 64, height 64 ]
        , Icons.notificationFilled [ width 64, height 64 ]
        , Icons.payCircleFilled [ width 64, height 64 ]
        , Icons.phoneFilled [ width 64, height 64 ]
        , Icons.pictureFilled [ width 64, height 64 ]
        , Icons.playSquareFilled [ width 64, height 64 ]
        , Icons.poundCircleFilled [ width 64, height 64 ]
        , Icons.printerFilled [ width 64, height 64 ]
        , Icons.profileFilled [ width 64, height 64 ]
        , Icons.projectFilled [ width 64, height 64 ]
        , Icons.propertySafetyFilled [ width 64, height 64 ]
        , Icons.pushpinFilled [ width 64, height 64 ]
        , Icons.qqCircleFilled [ width 64, height 64 ]
        , Icons.qqSquareFilled [ width 64, height 64 ]
        , Icons.readFilled [ width 64, height 64 ]
        , Icons.reconciliationFilled [ width 64, height 64 ]
        , Icons.redEnvelopeFilled [ width 64, height 64 ]
        , Icons.redditCircleFilled [ width 64, height 64 ]
        , Icons.redditSquareFilled [ width 64, height 64 ]
        , Icons.restFilled [ width 64, height 64 ]
        , Icons.robotFilled [ width 64, height 64 ]
        , Icons.rocketFilled [ width 64, height 64 ]
        , Icons.safetyCertificateFilled [ width 64, height 64 ]
        , Icons.saveFilled [ width 64, height 64 ]
        , Icons.scheduleFilled [ width 64, height 64 ]
        , Icons.securityScanFilled [ width 64, height 64 ]
        , Icons.settingFilled [ width 64, height 64 ]
        , Icons.shopFilled [ width 64, height 64 ]
        , Icons.shoppingFilled [ width 64, height 64 ]
        , Icons.signalFilled [ width 64, height 64 ]
        , Icons.sketchCircleFilled [ width 64, height 64 ]
        , Icons.sketchSquareFilled [ width 64, height 64 ]
        , Icons.skinFilled [ width 64, height 64 ]
        , Icons.slackCircleFilled [ width 64, height 64 ]
        , Icons.smileFilled [ width 64, height 64 ]
        , Icons.soundFilled [ width 64, height 64 ]
        , Icons.starFilled [ width 64, height 64 ]
        , Icons.switcherFilled [ width 64, height 64 ]
        , Icons.tabletFilled [ width 64, height 64 ]
        , Icons.tagFilled [ width 64, height 64 ]
        , Icons.tagsFilled [ width 64, height 64 ]
        , Icons.taobaoSquareFilled [ width 64, height 64 ]
        , Icons.thunderboltFilled [ width 64, height 64 ]
        , Icons.toolFilled [ width 64, height 64 ]
        , Icons.trademarkCircleFilled [ width 64, height 64 ]
        , Icons.trophyFilled [ width 64, height 64 ]
        , Icons.twitterCircleFilled [ width 64, height 64 ]
        , Icons.twitterSquareFilled [ width 64, height 64 ]
        , Icons.unlockFilled [ width 64, height 64 ]
        , Icons.usbFilled [ width 64, height 64 ]
        , Icons.videoCameraFilled [ width 64, height 64 ]
        , Icons.walletFilled [ width 64, height 64 ]
        , Icons.zhihuCircleFilled [ width 64, height 64 ]
        , Icons.zhihuSquareFilled [ width 64, height 64 ]
        ]
    , twoTone =
        [ Icons.accountBookTwoTone [ width 64, height 64 ]
        , Icons.alertTwoTone [ width 64, height 64 ]
        , Icons.apiTwoTone [ width 64, height 64 ]
        , Icons.appstoreTwoTone [ width 64, height 64 ]
        , Icons.audioTwoTone [ width 64, height 64 ]
        , Icons.bankTwoTone [ width 64, height 64 ]
        , Icons.bellTwoTone [ width 64, height 64 ]
        , Icons.bookTwoTone [ width 64, height 64 ]
        , Icons.bugTwoTone [ width 64, height 64 ]
        , Icons.buildTwoTone [ width 64, height 64 ]
        , Icons.bulbTwoTone [ width 64, height 64 ]
        , Icons.calculatorTwoTone [ width 64, height 64 ]
        , Icons.calendarTwoTone [ width 64, height 64 ]
        , Icons.cameraTwoTone [ width 64, height 64 ]
        , Icons.carTwoTone [ width 64, height 64 ]
        , Icons.carryOutTwoTone [ width 64, height 64 ]
        , Icons.ciCircleTwoTone [ width 64, height 64 ]
        , Icons.ciTwoTone [ width 64, height 64 ]
        , Icons.cloudTwoTone [ width 64, height 64 ]
        , Icons.codeTwoTone [ width 64, height 64 ]
        , Icons.compassTwoTone [ width 64, height 64 ]
        , Icons.contactsTwoTone [ width 64, height 64 ]
        , Icons.containerTwoTone [ width 64, height 64 ]
        , Icons.controlTwoTone [ width 64, height 64 ]
        , Icons.copyrightCircleTwoTone [ width 64, height 64 ]
        , Icons.copyrightTwoTone [ width 64, height 64 ]
        , Icons.creditCardTwoTone [ width 64, height 64 ]
        , Icons.crownTwoTone [ width 64, height 64 ]
        , Icons.customerServiceTwoTone [ width 64, height 64 ]
        , Icons.dashboardTwoTone [ width 64, height 64 ]
        , Icons.databaseTwoTone [ width 64, height 64 ]
        , Icons.dislikeTwoTone [ width 64, height 64 ]
        , Icons.dollarCircleTwoTone [ width 64, height 64 ]
        , Icons.dollarTwoTone [ width 64, height 64 ]
        , Icons.environmentTwoTone [ width 64, height 64 ]
        , Icons.euroCircleTwoTone [ width 64, height 64 ]
        , Icons.euroTwoTone [ width 64, height 64 ]
        , Icons.experimentTwoTone [ width 64, height 64 ]
        , Icons.eyeTwoTone [ width 64, height 64 ]
        , Icons.eyeInvisibleTwoTone [ width 64, height 64 ]
        , Icons.fileAddTwoTone [ width 64, height 64 ]
        , Icons.fileExcelTwoTone [ width 64, height 64 ]
        , Icons.fileExclamationTwoTone [ width 64, height 64 ]
        , Icons.fileTwoTone [ width 64, height 64 ]
        , Icons.fileImageTwoTone [ width 64, height 64 ]
        , Icons.fileMarkdownTwoTone [ width 64, height 64 ]
        , Icons.filePdfTwoTone [ width 64, height 64 ]
        , Icons.filePptTwoTone [ width 64, height 64 ]
        , Icons.fileTextTwoTone [ width 64, height 64 ]
        , Icons.fileUnknownTwoTone [ width 64, height 64 ]
        , Icons.fileWordTwoTone [ width 64, height 64 ]
        , Icons.fileZipTwoTone [ width 64, height 64 ]
        , Icons.filterTwoTone [ width 64, height 64 ]
        , Icons.fireTwoTone [ width 64, height 64 ]
        , Icons.flagTwoTone [ width 64, height 64 ]
        , Icons.folderAddTwoTone [ width 64, height 64 ]
        , Icons.folderTwoTone [ width 64, height 64 ]
        , Icons.folderOpenTwoTone [ width 64, height 64 ]
        , Icons.frownTwoTone [ width 64, height 64 ]
        , Icons.funnelPlotTwoTone [ width 64, height 64 ]
        , Icons.giftTwoTone [ width 64, height 64 ]
        , Icons.goldTwoTone [ width 64, height 64 ]
        , Icons.hddTwoTone [ width 64, height 64 ]
        , Icons.heartTwoTone [ width 64, height 64 ]
        , Icons.homeTwoTone [ width 64, height 64 ]
        , Icons.hourglassTwoTone [ width 64, height 64 ]
        , Icons.idcardTwoTone [ width 64, height 64 ]
        , Icons.insuranceTwoTone [ width 64, height 64 ]
        , Icons.interactionTwoTone [ width 64, height 64 ]
        , Icons.layoutTwoTone [ width 64, height 64 ]
        , Icons.likeTwoTone [ width 64, height 64 ]
        , Icons.lockTwoTone [ width 64, height 64 ]
        , Icons.mailTwoTone [ width 64, height 64 ]
        , Icons.medicineBoxTwoTone [ width 64, height 64 ]
        , Icons.mehTwoTone [ width 64, height 64 ]
        , Icons.messageTwoTone [ width 64, height 64 ]
        , Icons.mobileTwoTone [ width 64, height 64 ]
        , Icons.moneyCollectTwoTone [ width 64, height 64 ]
        , Icons.notificationTwoTone [ width 64, height 64 ]
        , Icons.phoneTwoTone [ width 64, height 64 ]
        , Icons.pictureTwoTone [ width 64, height 64 ]
        , Icons.playSquareTwoTone [ width 64, height 64 ]
        , Icons.poundCircleTwoTone [ width 64, height 64 ]
        , Icons.printerTwoTone [ width 64, height 64 ]
        , Icons.profileTwoTone [ width 64, height 64 ]
        , Icons.projectTwoTone [ width 64, height 64 ]
        , Icons.propertySafetyTwoTone [ width 64, height 64 ]
        , Icons.pushpinTwoTone [ width 64, height 64 ]
        , Icons.reconciliationTwoTone [ width 64, height 64 ]
        , Icons.redEnvelopeTwoTone [ width 64, height 64 ]
        , Icons.restTwoTone [ width 64, height 64 ]
        , Icons.rocketTwoTone [ width 64, height 64 ]
        , Icons.safetyCertificateTwoTone [ width 64, height 64 ]
        , Icons.saveTwoTone [ width 64, height 64 ]
        , Icons.scheduleTwoTone [ width 64, height 64 ]
        , Icons.securityScanTwoTone [ width 64, height 64 ]
        , Icons.settingTwoTone [ width 64, height 64 ]
        , Icons.shopTwoTone [ width 64, height 64 ]
        , Icons.shoppingTwoTone [ width 64, height 64 ]
        , Icons.skinTwoTone [ width 64, height 64 ]
        , Icons.smileTwoTone [ width 64, height 64 ]
        , Icons.soundTwoTone [ width 64, height 64 ]
        , Icons.starTwoTone [ width 64, height 64 ]
        , Icons.switcherTwoTone [ width 64, height 64 ]
        , Icons.tabletTwoTone [ width 64, height 64 ]
        , Icons.tagTwoTone [ width 64, height 64 ]
        , Icons.tagsTwoTone [ width 64, height 64 ]
        , Icons.thunderboltTwoTone [ width 64, height 64 ]
        , Icons.toolTwoTone [ width 64, height 64 ]
        , Icons.trademarkCircleTwoTone [ width 64, height 64 ]
        , Icons.trophyTwoTone [ width 64, height 64 ]
        , Icons.unlockTwoTone [ width 64, height 64 ]
        , Icons.usbTwoTone [ width 64, height 64 ]
        , Icons.videoCameraTwoTone [ width 64, height 64 ]
        , Icons.walletTwoTone [ width 64, height 64 ]
        ]
    }
